config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :haikus, only: [:index, :new, :create] do
    collection do
      post :confirm
    end
  end

  resources :comichaikus, only: [:index, :new, :create] do
    collection do
      post :confirm
    end
  end

  resources :songs, only: [:index, :new, :create] do
    collection do
      post :confirm
    end
  end

  root 'top#index'

  resources :skills, only: [:index] do
  end

end

app/models/comichaiku.rb
class Comichaiku < ActiveRecord::Base
end

app/models/haiku.rb
class Haiku < ActiveRecord::Base
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comichaikus_controller.rb
class ComichaikusController < ApplicationController
  def index
   @comichaikus = Comichaiku.all
  end

  def new
    @comichaiku = Comichaiku.new
  end

  def create
    Comichaiku.create(comichaikus_params)
    redirect_to comichaikus_path
  end

  def confirm
    @comichaiku = Comichaiku.new(comichaikus_params)
  end

  private
    def comichaikus_params
      params.require(:comichaiku).permit(:title, :content)
    end

end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController
  def index
   @haikus = Haiku.all
  end

  def new
    @haiku = Haiku.new
  end

  def create
    Haiku.create(haikus_params)
    redirect_to haikus_path
  end

  def confirm
    @haiku = Haiku.new(haikus_params)
  end

  private
    def haikus_params
      params.require(:haiku).permit(:title, :content)
    end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
   @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def create
    Song.create(songs_params)
    redirect_to songs_path
  end

  private
    def songs_params
      params.require(:song).permit(:title, :content)
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/comichaikus/_form.html.erb
  <%= form_for(@comichaiku, url: confirm_comichaikus_path) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>

app/views/comichaikus/confirm.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">

<h3>以下の内容で、送信する。</h3>

<%= form_for(@comichaiku) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>

  <!-- @blog.titleと@blog.contentとすることで、表示用の値を画面に出力しています。 -->
  <p>タイトル:<%= @comichaiku.title %></p>
  <p>本文:<%= @comichaiku.content %></p>
  <%= f.submit "登録する" %>
<% end %>

</div>
</div>

app/views/comichaikus/index.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">

<h1>川柳一覧</h1>

<% @comichaikus.each do |comichaiku| %>
  <h4><strong>タイトル:<%= comichaiku.title %></strong></h4>
  <p>本文:<%= comichaiku.content %></p>
<% end %>
<%= link_to "川柳を作成する", new_comichaiku_path %>
</div>
</div>

app/views/comichaikus/new.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<h2>川柳を作成する</h2>

<%= render 'form' %>

</div>
</div>

app/views/haikus/_form.html.erb
<%= form_for(@haiku, url: confirm_haikus_path) do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<%= f.label :content %>
<%= f.text_field :content %>
<br>
<%= f.submit %>
<% end %>

app/views/haikus/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@haiku) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>

  <!-- @blog.titleと@blog.contentとすることで、表示用の値を画面に出力しています。 -->
  <p>タイトル:<%= @haiku.title %></p>
  <p>本文:<%= @haiku.content %></p>
  <%= f.submit "登録する" %>
<% end %>

app/views/haikus/index.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<h1>俳句一覧</h1>

<% @haikus.each do |haiku| %>
  <p>タイトル:<%= haiku.title %></p>
  <p>本文:<%= haiku.content %></p>
<% end %>

<%= link_to "俳句を作成する", new_haiku_path %>
</div>
</div>

app/views/haikus/new.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<h2>俳句を作成する</h2>

<%= render 'form' %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rival</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/skills/index.html.erb
<!DOCTYPE html>
<html>
 <head>
  <meta charset="UTF-8">
   <title>not_lose</title>
   <link rel="stylesheet" href="style.css">
 </head>
 <body>
   <div class="skill_index">
    <img src="<%= asset_path "skillindex.jpg" %>"></A>
    <A Href="http://localhost:3000/songs" Target="_blank"><img src="<%= asset_path "song.gif" %>" class="song"></A>
    <A Href="http://localhost:3000/haikus" Target="_blank"><img src="<%= asset_path "haiku.gif" %>" class="haiku"></A>
    <A Href="http://localhost:3000/comichaikus" Target="_blank"><img src="<%= asset_path "comikuhaiku.gif" %>" class="senryu"></A>
   </div>
 </body>
</html>

app/views/songs/index.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<h1>歌一覧</h1>

<% @songs.each do |song| %>
  <p>タイトル:<%= song.title %></p>
  <p>本文:<%= song.content %></p>
<% end %>

<%= link_to "歌を作成する", new_song_path %>
</div>
</div>

app/views/songs/new.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<%= form_for(@song) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>
</div>
</div>

app/views/top/index.html.erb
<section class="main-header">
  <p class="flash"><%= notice %><%= alert %></p>
  <img src="<%= asset_path "achieve.png" %>">
</section>
<!DOCTYPE html>
<html>
 <head>
  <meta charset="UTF-8">
   <title>not_lose</title>
   <link rel="stylesheets" href="style.css">
 </head>
 <body>
   <div class="not_lose">
    <img src="<%= asset_path "girl_not_lose.jpg" %>"></A>
    <img src="<%= asset_path "raival_discover1.png" %>"class="absolute">
    <A Href="http://www.yahoo.co.jp/" Target="_blank"><img src="<%= asset_path "login1.png" %>" class="login"></A>
    <A Href="http://www.yahoo.co.jp/" Target="_blank"><img src="<%= asset_path "signup1.png" %>" class="signup"></A>
    <A Href="http://localhost:3000/skills" Target="_blank"><img src="<%= asset_path "enmoku1.png" %>" class="enmoku"></A>
    <img src="<%= asset_path "to_not.png" %>" class="to_not">
   </div>
 </body>
</html>